baseurl: "/openCPQ"
url: "http://webXcerpt.github.io"
title: "openCPQ"

exclude:
  - "README.md"
  - "Gemfile"
  - "params.json"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
